### ISSUE TITLE
怎么在windows build这个代码呀

### ISSUE THREAD

**Issue by harrisonGPU** [ejunjsh/kaleidoscope#1]
我想知道这个代码放到LLVM下面的哪里可以跑啊？

**Comment by ejunjsh** [comment]
我没有在window 上build过，我是在mac os build的

不用放到llvm里面啊，你下载我代码，然后创建一个build文件夹在我代码里面，进去，然后用cmake用我那个命令build就可以了，有可能要指定下llvm安装目录下这个LLVMConfig.cmake文件的地址。

**Comment by harrisonGPU** [comment]
老哥，我也尝试了，但还是不行，是不是什么 find_package
啥的找不到才这样的，${LLVM_INCLUDE_DIRS}这些我也不清楚设置没设置，太谢谢你了

IdiotSky ***@***.***> 于2022年10月12日周三 08:50写道：

**Comment by harrisonGPU** [comment]
> 我没有在window 上build过，我是在mac os build的
> 
> 不用放到llvm里面啊，你下载我代码，然后创建一个build文件夹在我代码里面，进去，然后用cmake用我那个命令build就可以了，有可能要指定下llvm安装目录下这个LLVMConfig.cmake文件的地址。

那估计是不是windows下面不行啊。。。。。。。

**Comment by ejunjsh** [comment]
clang++ -g *.cc `llvm-config --cxxflags --ldflags --system-libs --libs core orcjit native` -O3 -o toy
用上面这条命令试下，clang++ 和llvm-config 这个命令行工具应该在llvm 的bin目录里面，

**Comment by harrisonGPU** [comment]
> clang++ -g *.cc `llvm-config --cxxflags --ldflags --system-libs --libs core orcjit native` -O3 -o toy 用上面这条命令试下，clang++ 和llvm-config 这个命令行工具应该在llvm 的bin目录里面，

不对呀，是我运行你的project ，运行 cmake --build 跑不通，我觉得是CMakefiles.txt 里面的宏定义在Windows下面需要手动设置一下

**Comment by harrisonGPU** [comment]
老哥，我就是你GitHub发commont的那个人呀，请老哥出个window的教程好不好，我搞了一天了，还是有问题。。。。。。。。。。。。。。呜呜呜呜

IdiotSky ***@***.***> 于2022年10月12日周三 14:57写道：
